-- Add 27 distinct catalog products with Chinese and English storefront copy.

-- 数码电子
INSERT INTO products (id, category_id, name, name_en, subtitle, subtitle_en, description, description_en, price, original_price, stock, sales_count, rating, image_url, images_json, specs_json, tags_json, is_hot, is_new, created_at, updated_at) VALUES
('prod_038', 'cat_digital', 'Nintendo Switch OLED', 'Nintendo Switch OLED', '7英寸OLED屏 随时畅玩', '7-inch OLED display for play anywhere', '鲜艳OLED屏幕，支持掌机、桌面和电视三种模式', 'Vivid OLED display with handheld, tabletop, and TV play modes', 2399, 2699, 45, 1218, 4.8, 'https://via.placeholder.com/400', '[]', '{"screen":"7-inch OLED","storage":"64GB"}', '["游戏主机","OLED"]', 1, 0, datetime('now'), datetime('now')),
('prod_039', 'cat_digital', '罗技 MX Master 3S', 'Logitech MX Master 3S', '静音精准 高效办公', 'Quiet precision for productive work', '8K DPI传感器与静音按键，适合多设备办公', 'An 8K DPI sensor and quiet clicks for multi-device work', 699, 799, 85, 987, 4.7, 'https://via.placeholder.com/400', '[]', '{"connection":"Bluetooth / Logi Bolt","dpi":"8000"}', '["鼠标","办公"]', 0, 1, datetime('now'), datetime('now')),
('prod_040', 'cat_digital', '华为 MatePad 11.5', 'HUAWEI MatePad 11.5', '护眼大屏 学习创作', 'Eye-comfort large screen for study and creation', '11.5英寸高刷护眼屏，适合笔记、阅读与轻办公', 'An 11.5-inch high-refresh eye-comfort display for notes, reading, and light work', 1799, 2099, 65, 764, 4.6, 'https://via.placeholder.com/400', '[]', '{"display":"11.5-inch","refresh_rate":"120Hz"}', '["平板","学习"]', 0, 1, datetime('now'), datetime('now')),
('prod_041', 'cat_digital', 'JBL Flip 6 蓝牙音箱', 'JBL Flip 6 Bluetooth Speaker', '便携防水 澎湃音效', 'Portable waterproof sound with punch', 'IP67防尘防水设计，户外聚会也能享受立体音效', 'IP67 dust and water resistance delivers bold sound for outdoor gatherings', 899, 1099, 110, 1834, 4.7, 'https://via.placeholder.com/400', '[]', '{"waterproof":"IP67","playtime":"12 hours"}', '["音箱","户外"]', 1, 0, datetime('now'), datetime('now')),
('prod_042', 'cat_digital', '飞利浦 27英寸显示器', 'Philips 27-inch Monitor', '2K高清 低蓝光护眼', '2K clarity with low-blue-light comfort', '27英寸2K IPS屏幕，支持低蓝光模式与多场景办公', 'A 27-inch 2K IPS panel with low-blue-light mode for everyday work', 1299, 1599, 55, 645, 4.6, 'https://via.placeholder.com/400', '[]', '{"resolution":"2560x1440","panel":"IPS"}', '["显示器","2K"]', 0, 0, datetime('now'), datetime('now'));

-- 服饰鞋包
INSERT INTO products (id, category_id, name, name_en, subtitle, subtitle_en, description, description_en, price, original_price, stock, sales_count, rating, image_url, images_json, specs_json, tags_json, is_hot, is_new, created_at, updated_at) VALUES
('prod_043', 'cat_fashion', '优衣库圆领针织衫', 'UNIQLO Crew Neck Sweater', '柔软亲肤 通勤百搭', 'Soft, skin-friendly, and easy to style', '细腻针织面料与利落圆领，适合叠穿和日常通勤', 'Fine knit fabric and a clean crew neck for layering and daily commutes', 299, 399, 180, 2145, 4.7, 'https://via.placeholder.com/400', '[]', '{"material":"cotton blend","fit":"regular"}', '["针织衫","通勤"]', 1, 0, datetime('now'), datetime('now')),
('prod_044', 'cat_fashion', '萨洛蒙 XT-6 越野跑鞋', 'Salomon XT-6 Trail Shoes', '抓地稳定 城市户外', 'Stable grip from city streets to trails', '轻量缓震与耐磨鞋底，兼顾日常穿搭和轻越野', 'Light cushioning and a durable outsole for daily wear and light trails', 1399, 1599, 70, 893, 4.8, 'https://via.placeholder.com/400', '[]', '{"upper":"mesh","outsole":"Contagrip"}', '["跑鞋","户外"]', 0, 1, datetime('now'), datetime('now')),
('prod_045', 'cat_fashion', '蕉内空气棉家居服', 'Bananain Air Cotton Loungewear', '轻盈透气 舒适居家', 'Lightweight, breathable comfort at home', '空气棉面料柔软透气，宽松剪裁适合四季居家', 'Soft breathable air-cotton and a relaxed fit for year-round lounging', 269, 329, 140, 1678, 4.6, 'https://via.placeholder.com/400', '[]', '{"material":"air cotton","style":"two-piece set"}', '["家居服","舒适"]', 0, 0, datetime('now'), datetime('now')),
('prod_046', 'cat_fashion', 'Fjällräven Kånken 双肩包', 'Fjällräven Kånken Backpack', '轻便耐用 简约出行', 'Lightweight, durable, and ready to go', '经典方形包型，耐磨面料适合通勤、旅行和校园', 'The iconic square shape and durable fabric suit commutes, travel, and campus', 699, 799, 90, 1223, 4.7, 'https://via.placeholder.com/400', '[]', '{"capacity":"16L","material":"Vinylon F"}', '["双肩包","通勤"]', 0, 0, datetime('now'), datetime('now')),
('prod_047', 'cat_fashion', '周生生简约银项链', 'Chow Sang Sang Silver Necklace', '925银材质 日常点睛', '925 silver for an everyday finishing touch', '简约锁骨链设计，925银材质，适合日常叠戴', 'A minimalist 925 silver collarbone chain designed for everyday layering', 368, 468, 75, 536, 4.8, 'https://via.placeholder.com/400', '[]', '{"material":"925 sterling silver","length":"40cm + 5cm"}', '["饰品","银项链"]', 0, 1, datetime('now'), datetime('now'));

-- 家居生活
INSERT INTO products (id, category_id, name, name_en, subtitle, subtitle_en, description, description_en, price, original_price, stock, sales_count, rating, image_url, images_json, specs_json, tags_json, is_hot, is_new, created_at, updated_at) VALUES
('prod_048', 'cat_home', '膳魔师保温杯', 'Thermos Insulated Tumbler', '长效保温 轻巧随行', 'Long-lasting insulation, easy to carry', '不锈钢真空保温结构，适合通勤、健身与短途旅行', 'Stainless-steel vacuum insulation for commutes, workouts, and short trips', 199, 259, 220, 2890, 4.8, 'https://via.placeholder.com/400', '[]', '{"capacity":"500ml","material":"stainless steel"}', '["保温杯","随行"]', 1, 0, datetime('now'), datetime('now')),
('prod_049', 'cat_home', '乐扣乐扣玻璃保鲜盒', 'LocknLock Glass Food Container', '耐热玻璃 密封保鲜', 'Heat-resistant glass with a tight seal', '高硼硅玻璃搭配四面锁扣，适合备餐和冰箱收纳', 'Borosilicate glass and a four-sided lock for meal prep and fridge storage', 129, 169, 160, 1564, 4.7, 'https://via.placeholder.com/400', '[]', '{"capacity":"1L","material":"borosilicate glass"}', '["保鲜盒","厨房"]', 0, 0, datetime('now'), datetime('now')),
('prod_050', 'cat_home', '米家智能台灯 1S', 'Xiaomi Smart Desk Lamp 1S', '无级调光 智能护眼', 'Stepless dimming for smart eye comfort', '高显色灯珠支持无级调光，可通过米家应用控制', 'High color-rendering LEDs offer stepless dimming and Mi Home app control', 199, 249, 95, 1246, 4.6, 'https://via.placeholder.com/400', '[]', '{"color_rendering":"Ra 95","control":"Mi Home app"}', '["台灯","智能家居"]', 0, 1, datetime('now'), datetime('now')),
('prod_051', 'cat_home', '宜家波昂休闲椅', 'IKEA POÄNG Armchair', '弧形摇椅 舒适承托', 'Curved comfort with flexible support', '弯曲桦木框架配合高靠背坐垫，打造放松阅读角', 'A bent birch frame and high-back cushion create a relaxing reading spot', 899, 1099, 32, 485, 4.7, 'https://via.placeholder.com/400', '[]', '{"frame":"birch veneer","max_load":"170kg"}', '["休闲椅","客厅"]', 0, 0, datetime('now'), datetime('now')),
('prod_052', 'cat_home', 'Bose SoundLink Flex', 'Bose SoundLink Flex', '防水便携 自然音色', 'Waterproof portability with natural sound', '便携机身与PositionIQ技术，让不同摆放角度都有平衡听感', 'A portable body and PositionIQ technology deliver balanced sound in any position', 1199, 1399, 50, 678, 4.8, 'https://via.placeholder.com/400', '[]', '{"waterproof":"IP67","battery":"up to 12 hours"}', '["蓝牙音箱","便携"]', 0, 1, datetime('now'), datetime('now'));

-- 美妆护肤
INSERT INTO products (id, category_id, name, name_en, subtitle, subtitle_en, description, description_en, price, original_price, stock, sales_count, rating, image_url, images_json, specs_json, tags_json, is_hot, is_new, created_at, updated_at) VALUES
('prod_053', 'cat_beauty', '赫莲娜黑绷带面霜', 'Helena Rubinstein Replasty Cream', '高端修护 紧致弹润', 'Luxury repair for firm, supple skin', '丰润乳霜质地，帮助改善干燥与粗糙肤感', 'A rich cream texture that helps improve the feel of dryness and roughness', 3580, 3980, 25, 379, 4.9, 'https://via.placeholder.com/400', '[]', '{"volume":"50ml","skin_type":"dry / normal"}', '["面霜","修护"]', 1, 0, datetime('now'), datetime('now')),
('prod_054', 'cat_beauty', '珂润润浸保湿乳液', 'Curél Intensive Moisture Lotion', '温和保湿 敏感肌适用', 'Gentle moisture for sensitive skin', '清爽易吸收的保湿乳液，帮助维持肌肤水润舒适', 'A lightweight moisturizing lotion that helps keep skin hydrated and comfortable', 188, 228, 150, 2534, 4.7, 'https://via.placeholder.com/400', '[]', '{"volume":"120ml","skin_type":"sensitive skin"}', '["乳液","敏感肌"]', 1, 0, datetime('now'), datetime('now')),
('prod_055', 'cat_beauty', '理肤泉 B5 修复霜', 'La Roche-Posay Cicaplast Baume B5', '舒缓修护 多效保湿', 'Soothing repair with multi-use moisture', '轻盈膏体可用于面部和身体局部干燥护理', 'A lightweight balm for targeted dry areas on face and body', 159, 189, 210, 3678, 4.8, 'https://via.placeholder.com/400', '[]', '{"volume":"40ml","texture":"balm"}', '["修复霜","保湿"]', 1, 0, datetime('now'), datetime('now')),
('prod_056', 'cat_beauty', '欧舒丹乳木果护手霜', 'L''Occitane Shea Hand Cream', '滋润不黏腻 细腻留香', 'Rich moisture without a sticky feel', '乳木果油配方滋养双手，适合秋冬和频繁洗手后使用', 'Shea butter nourishes hands after frequent washing or in colder seasons', 120, 150, 175, 1945, 4.7, 'https://via.placeholder.com/400', '[]', '{"volume":"30ml","key_ingredient":"shea butter"}', '["护手霜","滋润"]', 0, 0, datetime('now'), datetime('now')),
('prod_057', 'cat_beauty', '植村秀砍刀眉笔', 'Shu Uemura Hard Formula Eyebrow Pencil', '自然持久 精准勾勒', 'Natural, lasting definition with precision', '独特砍刀笔芯便于勾勒毛流感，打造自然立体眉形', 'Its distinctive blade-shaped lead creates natural hair-like strokes', 260, 300, 115, 879, 4.6, 'https://via.placeholder.com/400', '[]', '{"shade":"seal brown","type":"eyebrow pencil"}', '["眉笔","彩妆"]', 0, 1, datetime('now'), datetime('now')),
('prod_058', 'cat_beauty', '戴森 Supersonic 吹风机', 'Dyson Supersonic Hair Dryer', '快速干发 智能控温', 'Fast drying with intelligent heat control', '高速数码马达与智能温控，减少高温吹风带来的不适', 'A high-speed digital motor and intelligent heat control offer fast, comfortable drying', 2990, 3290, 35, 654, 4.8, 'https://via.placeholder.com/400', '[]', '{"power":"1600W","attachments":"5"}', '["美发","吹风机"]', 0, 1, datetime('now'), datetime('now'));

-- 食品饮料
INSERT INTO products (id, category_id, name, name_en, subtitle, subtitle_en, description, description_en, price, original_price, stock, sales_count, rating, image_url, images_json, specs_json, tags_json, is_hot, is_new, created_at, updated_at) VALUES
('prod_059', 'cat_food', '农夫山泉 NFC 橙汁', 'Nongfu Spring NFC Orange Juice', '鲜榨果汁 清甜自然', 'Freshly squeezed juice with natural sweetness', 'NFC非浓缩还原工艺，保留橙子清新果香', 'NFC processing preserves the fresh aroma of oranges without reconstitution', 39.9, 49.9, 260, 2345, 4.7, 'https://via.placeholder.com/400', '[]', '{"volume":"300ml x 4","type":"NFC juice"}', '["果汁","饮料"]', 0, 1, datetime('now'), datetime('now')),
('prod_060', 'cat_food', '五芳斋鲜肉粽', 'Wufangzhai Fresh Pork Rice Dumplings', '糯香软糯 咸鲜饱满', 'Tender sticky rice with savory filling', '精选糯米与鲜肉馅料，传统风味加热即食', 'Selected sticky rice and pork filling in a traditional, heat-and-eat recipe', 69, 89, 190, 1765, 4.6, 'https://via.placeholder.com/400', '[]', '{"pack":"100g x 6","flavor":"fresh pork"}', '["粽子","速食"]', 0, 0, datetime('now'), datetime('now')),
('prod_061', 'cat_food', '百事无糖可乐', 'Pepsi Zero Sugar Cola', '冰爽气泡 零糖轻负担', 'Crisp bubbles with zero sugar', '零糖配方搭配清爽气泡，适合聚餐与日常冷饮', 'A zero-sugar formula with refreshing bubbles for meals and everyday chilling', 45, 59, 480, 3987, 4.5, 'https://via.placeholder.com/400', '[]', '{"volume":"330ml x 12","sugar":"zero sugar"}', '["可乐","零糖"]', 1, 0, datetime('now'), datetime('now')),
('prod_062', 'cat_food', '比比赞冻干草莓', 'Bibizan Freeze-dried Strawberries', '整颗冻干 酸甜酥脆', 'Whole freeze-dried berries, sweet and crisp', '整颗草莓低温冻干，保留果香与轻盈酥脆口感', 'Whole strawberries are freeze-dried at low temperature for fruity, crisp bites', 36.9, 45.9, 230, 2145, 4.7, 'https://via.placeholder.com/400', '[]', '{"net_weight":"60g","type":"freeze-dried fruit"}', '["零食","冻干"]', 0, 1, datetime('now'), datetime('now')),
('prod_063', 'cat_food', '瑞幸挂耳咖啡', 'Luckin Drip Coffee', '现磨风味 便捷手冲', 'Fresh-ground flavor in a convenient drip bag', '阿拉比卡拼配咖啡粉，办公室和旅行中都能轻松冲泡', 'Arabica blend coffee grounds that brew easily at the office or while traveling', 59, 79, 300, 1842, 4.6, 'https://via.placeholder.com/400', '[]', '{"pack":"10 bags","roast":"medium"}', '["咖啡","挂耳"]', 0, 0, datetime('now'), datetime('now')),
('prod_064', 'cat_food', '良品铺子海苔脆片', 'Bestore Crispy Seaweed Snacks', '轻薄酥脆 海苔鲜香', 'Thin, crisp snacks with savory seaweed', '烘烤工艺带来轻盈脆感，是追剧和下午茶的方便零食', 'Baked for a light crunch, these are easy snacks for movies and afternoon tea', 29.9, 39.9, 350, 2768, 4.6, 'https://via.placeholder.com/400', '[]', '{"net_weight":"72g","flavor":"original"}', '["海苔","零食"]', 0, 1, datetime('now'), datetime('now'));
