-- Expand inferred product types within the existing top-level categories only.
-- No new categories are created by this migration.

-- 数码电子：手机、笔记本、平板、智能手表、降噪耳机均补齐至至少三款。
INSERT INTO products (id, category_id, name, name_en, subtitle, subtitle_en, description, description_en, price, original_price, stock, sales_count, rating, image_url, images_json, specs_json, tags_json, is_hot, is_new, created_at, updated_at) VALUES
('prod_065', 'cat_digital', '三星 Galaxy S24', 'Samsung Galaxy S24', '旗舰影像 AI 智能体验', 'Flagship imaging with AI-powered features', '紧凑旗舰机身，配备高亮度屏幕与多场景智能功能', 'A compact flagship with a bright display and versatile AI features', 5499, 5999, 60, 872, 4.7, 'https://via.placeholder.com/400', '[]', '{"storage":"256GB","display":"6.2-inch AMOLED"}', '["手机","AI"]', 1, 1, datetime('now'), datetime('now')),
('prod_066', 'cat_digital', 'OPPO Find X7', 'OPPO Find X7', '超光影三主摄 流畅旗舰', 'Triple-camera imaging in a smooth flagship', '全焦段影像系统与高性能芯片，适合日常创作和娱乐', 'A versatile camera system and high-performance chip for creation and entertainment', 3999, 4499, 72, 654, 4.6, 'https://via.placeholder.com/400', '[]', '{"storage":"256GB","camera":"triple camera"}', '["手机","影像"]', 0, 1, datetime('now'), datetime('now')),
('prod_067', 'cat_digital', '联想小新 Pro 14', 'Lenovo Xiaoxin Pro 14', '高性能轻薄本 办公创作', 'Powerful lightweight laptop for work and creation', '14英寸高分辨率屏幕与轻薄机身，满足移动办公需求', 'A high-resolution 14-inch display in a slim chassis for mobile work', 5299, 5999, 48, 718, 4.7, 'https://via.placeholder.com/400', '[]', '{"display":"14-inch 2.8K","memory":"32GB"}', '["笔记本","办公"]', 0, 1, datetime('now'), datetime('now')),
('prod_068', 'cat_digital', '华硕灵耀 14', 'ASUS Zenbook 14', 'OLED屏幕 轻巧续航', 'OLED clarity with lightweight endurance', 'OLED屏幕呈现鲜明色彩，适合差旅和多任务处理', 'An OLED display with vivid color in a travel-friendly multitasking laptop', 6499, 7199, 38, 432, 4.7, 'https://via.placeholder.com/400', '[]', '{"display":"14-inch OLED","weight":"1.2kg"}', '["笔记本","OLED"]', 0, 0, datetime('now'), datetime('now')),
('prod_069', 'cat_digital', '三星 Galaxy Tab S9', 'Samsung Galaxy Tab S9', '旗舰平板 防水高刷屏', 'Flagship tablet with a water-resistant high-refresh display', '11英寸AMOLED屏幕支持S Pen，学习创作更从容', 'An 11-inch AMOLED display with S Pen support for study and creation', 5799, 6299, 40, 359, 4.8, 'https://via.placeholder.com/400', '[]', '{"display":"11-inch AMOLED","waterproof":"IP68"}', '["平板","创作"]', 0, 1, datetime('now'), datetime('now')),
('prod_070', 'cat_digital', '华为 Watch GT 5', 'HUAWEI Watch GT 5', '运动健康 长续航监测', 'Fitness and health tracking with long battery life', '多维运动记录与健康趋势管理，适合全天候佩戴', 'Multi-dimensional activity tracking and health trends for all-day wear', 1488, 1688, 88, 945, 4.7, 'https://via.placeholder.com/400', '[]', '{"display":"1.43-inch AMOLED","battery":"up to 14 days"}', '["智能手表","运动"]', 1, 1, datetime('now'), datetime('now')),
('prod_071', 'cat_digital', '小米 Watch 2 Pro', 'Xiaomi Watch 2 Pro', '独立定位 智能运动', 'Standalone positioning for smart workouts', '支持运动数据记录、定位与常用应用通知', 'Tracks workouts and location while keeping essential app notifications close', 1299, 1499, 96, 687, 4.6, 'https://via.placeholder.com/400', '[]', '{"display":"1.43-inch AMOLED","positioning":"dual-band GNSS"}', '["智能手表","定位"]', 0, 0, datetime('now'), datetime('now')),
('prod_072', 'cat_digital', 'Bose QuietComfort Ultra', 'Bose QuietComfort Ultra Headphones', '沉浸降噪 空间音频', 'Immersive noise cancellation and spatial audio', '包耳式设计搭配沉浸空间音频，适合通勤和长途旅行', 'Over-ear comfort and immersive audio for commutes and long trips', 3499, 3799, 35, 426, 4.8, 'https://via.placeholder.com/400', '[]', '{"battery":"up to 24 hours","type":"over-ear"}', '["耳机","降噪"]', 0, 1, datetime('now'), datetime('now'));

-- 服饰鞋包：包袋、裤装与家居服均补齐至至少三款。
INSERT INTO products (id, category_id, name, name_en, subtitle, subtitle_en, description, description_en, price, original_price, stock, sales_count, rating, image_url, images_json, specs_json, tags_json, is_hot, is_new, created_at, updated_at) VALUES
('prod_073', 'cat_fashion', 'Longchamp 饺子包', 'Longchamp Le Pliage Tote', '轻便折叠 通勤实用', 'Lightweight foldable tote for everyday use', '尼龙材质轻盈耐用，大容量设计适合通勤和短途出行', 'Durable lightweight nylon and generous capacity for commutes and short trips', 990, 1190, 82, 745, 4.7, 'https://via.placeholder.com/400', '[]', '{"material":"nylon","size":"medium"}', '["包袋","通勤"]', 0, 1, datetime('now'), datetime('now')),
('prod_074', 'cat_fashion', '优衣库宽腿牛仔裤', 'UNIQLO Wide Leg Jeans', '高腰宽松 复古百搭', 'High-rise relaxed denim with retro versatility', '舒适宽腿版型与挺括牛仔面料，轻松搭配日常造型', 'A relaxed high-rise silhouette in structured denim for everyday outfits', 399, 499, 135, 1643, 4.6, 'https://via.placeholder.com/400', '[]', '{"fit":"wide leg","material":"cotton denim"}', '["裤装","牛仔裤"]', 1, 0, datetime('now'), datetime('now')),
('prod_075', 'cat_fashion', 'Lululemon City Sweat 长裤', 'Lululemon City Sweat Joggers', '柔软卫裤 休闲通勤', 'Soft joggers for casual commutes', '棉感面料与锥形剪裁，兼顾居家舒适和外出利落', 'Cotton-soft fabric and a tapered fit balance comfort at home with a polished look', 880, 980, 70, 536, 4.7, 'https://via.placeholder.com/400', '[]', '{"fit":"tapered","material":"cotton blend"}', '["裤装","卫裤"]', 0, 1, datetime('now'), datetime('now')),
('prod_076', 'cat_fashion', '内外柔软睡衣套装', 'NEIWAI Soft Pajama Set', '亲肤莫代尔 舒展好眠', 'Skin-friendly modal for restful sleep', '柔软莫代尔面料搭配宽松剪裁，适合居家休息', 'Soft modal fabric and a relaxed fit for comfortable time at home', 359, 429, 120, 932, 4.7, 'https://via.placeholder.com/400', '[]', '{"material":"modal","style":"two-piece set"}', '["家居服","睡衣"]', 0, 1, datetime('now'), datetime('now')),
('prod_077', 'cat_fashion', '无印良品双层纱睡衣', 'MUJI Double Gauze Pajamas', '透气双层纱 四季舒适', 'Breathable double gauze for year-round comfort', '双层棉纱轻盈透气，适合春夏和空调房穿着', 'Lightweight double-layer cotton gauze is ideal for spring, summer, and air-conditioned rooms', 298, 358, 150, 1087, 4.6, 'https://via.placeholder.com/400', '[]', '{"material":"cotton gauze","style":"two-piece set"}', '["家居服","透气"]', 0, 0, datetime('now'), datetime('now'));

-- 家居生活：空气净化器、扫地机器人与咖啡机均补齐至至少三款。
INSERT INTO products (id, category_id, name, name_en, subtitle, subtitle_en, description, description_en, price, original_price, stock, sales_count, rating, image_url, images_json, specs_json, tags_json, is_hot, is_new, created_at, updated_at) VALUES
('prod_078', 'cat_home', '飞利浦空气净化器 800i', 'Philips Air Purifier 800i', '高效过滤 智能空气监测', 'Efficient filtration with smart air monitoring', '多重滤网过滤颗粒物与异味，实时显示室内空气状态', 'Multi-layer filters capture particles and odors while displaying indoor air status', 1799, 2099, 48, 652, 4.7, 'https://via.placeholder.com/400', '[]', '{"coverage":"49m²","filter":"HEPA"}', '["空气净化器","智能家居"]', 0, 1, datetime('now'), datetime('now')),
('prod_079', 'cat_home', '布鲁雅尔 Blue Max 3250i', 'Blueair Blue Max 3250i', '静音净化 北欧简约', 'Quiet purification in a Nordic design', '高速净化模式搭配低噪运行，适合卧室和客厅使用', 'Fast cleaning modes and quiet operation for bedrooms and living rooms', 2299, 2599, 30, 284, 4.8, 'https://via.placeholder.com/400', '[]', '{"coverage":"43m²","noise":"23dB"}', '["空气净化器","静音"]', 0, 0, datetime('now'), datetime('now')),
('prod_080', 'cat_home', '石头 P10S Pro 扫地机器人', 'Roborock P10S Pro Robot Vacuum', '智能避障 自动集尘', 'Smart obstacle avoidance with auto-emptying', '激光导航规划全屋清扫路线，扫拖后自动回洗集尘', 'Laser navigation maps whole-home cleaning and returns for washing and emptying', 3799, 4299, 35, 518, 4.8, 'https://via.placeholder.com/400', '[]', '{"navigation":"LiDAR","station":"auto empty and wash"}', '["扫地机器人","智能家居"]', 1, 1, datetime('now'), datetime('now')),
('prod_081', 'cat_home', '科沃斯 T20 扫地机器人', 'Ecovacs T20 Robot Vacuum', '热水洗拖布 深度清洁', 'Hot-water mop washing for deep cleaning', '自动抬升拖布并以热水清洗，减少地面二次污染', 'Automatically lifts mops and washes them with hot water to support cleaner floors', 3499, 3999, 40, 476, 4.7, 'https://via.placeholder.com/400', '[]', '{"mop_washing":"hot water","navigation":"laser"}', '["扫地机器人","扫拖"]', 0, 1, datetime('now'), datetime('now')),
('prod_082', 'cat_home', '德龙 Magnifica 咖啡机', 'DeLonghi Magnifica Coffee Machine', '现磨意式 一键奶咖', 'Fresh-ground espresso with one-touch milk coffee', '内置磨豆器与奶泡系统，在家轻松制作意式咖啡', 'A built-in grinder and milk system make espresso drinks easy at home', 4299, 4999, 26, 245, 4.8, 'https://via.placeholder.com/400', '[]', '{"pressure":"15 bar","grinder":"integrated"}', '["咖啡机","现磨"]', 0, 1, datetime('now'), datetime('now')),
('prod_083', 'cat_home', '飞利浦全自动咖啡机', 'Philips Fully Automatic Coffee Machine', '现磨萃取 醇香拿铁', 'Fresh-ground extraction for rich lattes', '触控菜单可选择多种咖啡饮品，日常清洁更方便', 'A touch menu offers multiple coffee drinks with convenient everyday cleaning', 3699, 4299, 28, 319, 4.7, 'https://via.placeholder.com/400', '[]', '{"drink_options":"5","milk_system":"LatteGo"}', '["咖啡机","全自动"]', 0, 0, datetime('now'), datetime('now'));

-- 美妆护肤：防晒、护发工具与面膜均补齐至至少三款。
INSERT INTO products (id, category_id, name, name_en, subtitle, subtitle_en, description, description_en, price, original_price, stock, sales_count, rating, image_url, images_json, specs_json, tags_json, is_hot, is_new, created_at, updated_at) VALUES
('prod_084', 'cat_beauty', '安热沙小金瓶防晒', 'Anessa Perfect UV Sunscreen Milk', '高倍防晒 清爽耐汗', 'High-protection sunscreen with a fresh, sweat-resistant finish', '水乳质地易推开，适合通勤和户外活动前使用', 'A fluid texture that spreads easily for commuting and outdoor days', 228, 268, 145, 2456, 4.8, 'https://via.placeholder.com/400', '[]', '{"volume":"60ml","spf":"SPF50+ PA++++"}', '["防晒","耐汗"]', 1, 0, datetime('now'), datetime('now')),
('prod_085', 'cat_beauty', '碧柔水感防晒啫喱', 'Biore UV Aqua Rich Gel', '水感轻薄 日常防晒', 'Watery, lightweight everyday sun protection', '清爽啫喱质地快速成膜，适合妆前和日常补涂', 'A refreshing gel that sets quickly for makeup prep and daily reapplication', 89, 109, 220, 3654, 4.7, 'https://via.placeholder.com/400', '[]', '{"volume":"90ml","spf":"SPF50+ PA++++"}', '["防晒","水感"]', 1, 0, datetime('now'), datetime('now')),
('prod_086', 'cat_beauty', '理肤泉大哥大防晒', 'La Roche-Posay Anthelios Sunscreen', '广谱防护 敏感肌友好', 'Broad-spectrum protection suitable for sensitive skin', '轻薄配方提供日常广谱防护，适合需要温和护理的人群', 'A lightweight formula provides broad-spectrum daily protection with gentle care', 198, 238, 135, 1832, 4.7, 'https://via.placeholder.com/400', '[]', '{"volume":"50ml","spf":"SPF50+"}', '["防晒","敏感肌"]', 0, 1, datetime('now'), datetime('now')),
('prod_087', 'cat_beauty', 'GHD Platinum+ 直发器', 'GHD Platinum+ Hair Styler', '智能控温 顺滑造型', 'Intelligent heat control for smooth styling', '恒温造型减少反复拉扯，轻松打造直发或微卷', 'Consistent heat makes straight or softly curled styles easier to create', 2199, 2499, 35, 342, 4.7, 'https://via.placeholder.com/400', '[]', '{"temperature":"185°C","type":"hair styler"}', '["美发","直发器"]', 0, 1, datetime('now'), datetime('now')),
('prod_088', 'cat_beauty', '飞利浦负离子卷发棒', 'Philips Ionic Curling Iron', '恒温卷发 柔亮不毛躁', 'Controlled curls with ionic shine', '多档温控配合负离子护理，打造自然卷度与光泽', 'Multiple heat settings and ionic care create natural curls with shine', 399, 499, 90, 625, 4.6, 'https://via.placeholder.com/400', '[]', '{"barrel":"32mm","temperature":"160-200°C"}', '["美发","卷发棒"]', 0, 0, datetime('now'), datetime('now')),
('prod_089', 'cat_beauty', 'SK-II 前男友面膜', 'SK-II Facial Treatment Mask', '密集补水 焕亮肤感', 'Intensive hydration for a refreshed glow', '浸润精华的贴片面膜，为重要场合前提供密集补水护理', 'An essence-soaked sheet mask for an intensive hydration boost before special occasions', 799, 899, 68, 763, 4.8, 'https://via.placeholder.com/400', '[]', '{"pack":"6 sheets","type":"sheet mask"}', '["面膜","补水"]', 0, 1, datetime('now'), datetime('now')),
('prod_090', 'cat_beauty', '美迪惠尔积雪草面膜', 'Mediheal Cica Sheet Mask', '舒缓保湿 清新贴肤', 'Soothing hydration with a fresh feel', '积雪草精华搭配柔软膜布，适合日常舒缓补水', 'Centella essence and a soft sheet make daily soothing hydration simple', 89, 109, 240, 2897, 4.6, 'https://via.placeholder.com/400', '[]', '{"pack":"10 sheets","key_ingredient":"centella"}', '["面膜","舒缓"]', 1, 0, datetime('now'), datetime('now'));

-- 食品饮料：果汁、坚果、咖啡与巧克力均补齐至至少三款。
INSERT INTO products (id, category_id, name, name_en, subtitle, subtitle_en, description, description_en, price, original_price, stock, sales_count, rating, image_url, images_json, specs_json, tags_json, is_hot, is_new, created_at, updated_at) VALUES
('prod_091', 'cat_food', '汇源 100%苹果汁', 'Huiyuan 100% Apple Juice', '纯正果香 清甜顺口', 'Pure apple flavor with gentle sweetness', '100%苹果汁口感清爽，适合早餐和家庭分享', 'Refreshing 100% apple juice for breakfast and family sharing', 32.9, 42.9, 280, 1967, 4.6, 'https://via.placeholder.com/400', '[]', '{"volume":"1L","fruit_content":"100%"}', '["果汁","饮料"]', 0, 0, datetime('now'), datetime('now')),
('prod_092', 'cat_food', '味全葡萄汁', 'Weichuan Grape Juice', '浓郁葡萄 清爽易饮', 'Rich grape flavor, easy to enjoy', '饱满葡萄风味与清爽口感，冰镇后风味更佳', 'Full grape flavor with a refreshing finish that is especially good chilled', 35.9, 45.9, 240, 1456, 4.6, 'https://via.placeholder.com/400', '[]', '{"volume":"1L","flavor":"grape"}', '["果汁","饮料"]', 0, 1, datetime('now'), datetime('now')),
('prod_093', 'cat_food', '沃隆每日坚果', 'Wolong Daily Nuts', '科学配比 每日营养', 'Balanced daily nutrition in individual packs', '多种坚果与果干独立包装，方便控制每日食用量', 'Nuts and dried fruit are individually packed for easy daily portions', 119, 149, 190, 3278, 4.8, 'https://via.placeholder.com/400', '[]', '{"pack":"25g x 30","type":"mixed nuts"}', '["坚果","零食"]', 1, 0, datetime('now'), datetime('now')),
('prod_094', 'cat_food', '洽洽每日坚果', 'ChaCheer Daily Nuts', '坚果果干 便携小包装', 'Nuts and fruit in convenient small packs', '精选坚果搭配果干，适合作为办公室和出行加餐', 'Selected nuts and fruit make a convenient snack for work and travel', 99, 129, 210, 2143, 4.7, 'https://via.placeholder.com/400', '[]', '{"pack":"20g x 30","type":"mixed nuts"}', '["坚果","加餐"]', 0, 0, datetime('now'), datetime('now')),
('prod_095', 'cat_food', '雀巢金牌速溶咖啡', 'Nescafé Gold Instant Coffee', '醇香速溶 便捷冲泡', 'Rich instant coffee with easy brewing', '冻干咖啡颗粒香气浓郁，热水冲泡即可享用', 'Freeze-dried coffee granules provide a rich aroma with simple hot-water brewing', 69, 89, 260, 2345, 4.6, 'https://via.placeholder.com/400', '[]', '{"net_weight":"100g","type":"instant coffee"}', '["咖啡","速溶"]', 0, 0, datetime('now'), datetime('now')),
('prod_096', 'cat_food', 'UCC 职人咖啡', 'UCC Craftsman Coffee', '日式焙煎 香醇平衡', 'Japanese roast with balanced aroma', '中度烘焙风味平衡，适合早餐和午后咖啡时光', 'A balanced medium roast for breakfast and afternoon coffee breaks', 78, 98, 180, 1298, 4.7, 'https://via.placeholder.com/400', '[]', '{"net_weight":"90g","roast":"medium"}', '["咖啡","日式焙煎"]', 0, 1, datetime('now'), datetime('now')),
('prod_097', 'cat_food', '德芙丝滑牛奶巧克力', 'Dove Silky Milk Chocolate', '丝滑醇厚 分享装', 'Smooth, rich milk chocolate for sharing', '细腻牛奶巧克力口感，适合日常零食和节日分享', 'Smooth milk chocolate for everyday treats and festive sharing', 45, 59, 320, 3567, 4.7, 'https://via.placeholder.com/400', '[]', '{"net_weight":"252g","flavor":"milk chocolate"}', '["巧克力","零食"]', 1, 0, datetime('now'), datetime('now')),
('prod_098', 'cat_food', '费列罗榛果巧克力', 'Ferrero Rocher Hazelnut Chocolates', '榛果夹心 节日礼赠', 'Hazelnut centers for festive gifting', '榛果威化夹心与巧克力外层，适合礼赠和分享', 'Hazelnut wafer centers in chocolate shells for gifting and sharing', 89, 109, 190, 2789, 4.8, 'https://via.placeholder.com/400', '[]', '{"pack":"16 pieces","flavor":"hazelnut"}', '["巧克力","礼盒"]', 1, 0, datetime('now'), datetime('now')),
('prod_099', 'cat_food', '明治黑巧克力', 'Meiji Dark Chocolate', '微苦醇香 轻享可可', 'Balanced dark cocoa with a gentle bitterness', '可可风味浓郁、甜度适中，适合搭配咖啡享用', 'Rich cocoa and balanced sweetness pair well with coffee', 39.9, 49.9, 245, 1876, 4.6, 'https://via.placeholder.com/400', '[]', '{"net_weight":"50g x 3","cocoa":"72%"}', '["巧克力","黑巧"]', 0, 1, datetime('now'), datetime('now'));
